import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import SiteProgressBar from "@/components/partials/SiteProgressBar";
import Nav from "@/components/layout/Nav/Nav";
import getToken from "@/utils/helpers/getToken";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const token = getToken();

  return (
    <html lang="en">
      <body className={inter.className}>
        <Nav token={token} />
        {children}
        <ToastContainer />
        <SiteProgressBar />
      </body>
    </html>
  );
}
